version: "3.7"
services:
  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=kiosk
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  nats:
    image: nats:2.1.0-scratch
    container_name: nats
    ports:
      - 127.0.0.1:4222:4222
      - 127.0.0.1:6222:6222
      - 127.0.0.1:8222:8222
