### Create comment request. Creates a new comment with provided values.
POST http://localhost:8080/v1/comments
Content-Type: application/json; charset=utf-8

{
    "ticket_id": "10",
    "owner": "user@example.com",
    "content": "Hello, i have some technical issue with your API documentation. Please help!",
    "metadata": "{\"ip\": \"185.186.187.188\"}"
}

Notes
owner: Who is this comment from?

HTTP/1.1 200 OK
{}

### Update comment request. Updates an already exists comment with provided values.
PUT http://localhost:8080/v1/comments
Content-Type: application/json; charset=utf-8

{
    "id": "10",
    "metadata": ""
}

HTTP/1.1 200 OK
{}

### Delete comment request.
DELETE http://localhost:8080/v1/tickets/10

HTTP/1.1 200 OK
{}
