### Echo request. Appropriate for health checking of kiosk service.
POST http://localhost:8080/v1/echo
Content-Type: application/json; charset=utf-8

{
    "content": "Hi"
}

# Response
# HTTP/1.1 200 OK
# {
#   "content": "Hi"
# }
