### Create ticket request. Creates a new ticket with provided values.
POST http://localhost:8080/v1/tickets
Content-Type: application/json; charset=utf-8

{
    "issuer": "Ticketing System",
    "owner": "user@example.com",
    "subject": "Technical Issue!",
    "content": "Hello, i have some technical issue with your API documentation. Please help!",
    "metadata": "{\"ip\": \"185.186.187.188\"}",
    "ticket_importance_level": 2
}

# Notes
# issuer: The name of your company or name of microservice who is creating the ticket.
# owner: Who is this ticket for?
# ticket_importance_level: 0 for LOW, 1 for MEDIUM and 2 for HIGH.

# Response
# HTTP/1.1 200 OK
# {}
